project:
  type: book
  output-dir: docs

book:
  title: "Course Notes for 431"
  author: "Thomas E. Love, Ph.D."
  date: "2022-08-27"
  search: true
  downloads: [pdf]
  output-file: "431-notes"
  chapters:
    - index.qmd
    - int_r_setup.qmd
    - 01-datascience.qmd
    - part: "Part A. Exploring Data"
      chapters:
        - 02-penguins1.qmd
        - 03-penguins2.qmd
        - 04-nhanes.qmd
        - 05-data_types.qmd
        - 06-nhanes_cc.qmd
        - 07-summarizing_quantities.qmd
        - 08-summarizing_categories.qmd
        - 09-missing_data.qmd
        - 10-nnyfs_foundations.qmd
        - 11-assessingnormality.qmd
        - 12-straightlinemodels.qmd
        - 13-linear_trans.qmd
        - 14-crabs.qmd
        - 15-hydrate.qmd
        - 16-wcgs.qmd
    - part: "Part B. Comparing Summaries"
      chapters:
        - partBhold.qmd
    ##    - 17-ci_for_mean.qmd
    ##    - 18-ibuprofen_sepsis.qmd
    ##    - 19-pairedsamples.qmd
    ##    - 20-samplesize.qmd
    ##    - 21-examples_2means.qmd
    ##    - 22-anova.qmd
    ##    - 23-one_proportion.qmd
    ##    - 24-comparing_rates.qmd
    ##    - 25-power_for_rates.qmd
    ##    - 26-contingency_tables.qmd
    - part: "Part C. Building Models"
      chapters: 
        - partChold.qmd
##        - 27-mult_reg_intro.qmd
##        - 28-regr_diagnostics.qmd
##        - 29-prediction_wcgs.qmd
##        - 30-galapagos.qmd
##        - 31-emp_bmi.qmd
##        - 32-nonlinearity.qmd
##        - 33-olsfits.qmd
  appendices:
    - 98_gettingdataintoR.qmd
    - 99_sessioninfo.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: source

